# Generated by Django 4.2.6 on 2023-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_mebel_options_mebel_parse_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['parse_datetime', '-price'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterField(
            model_name='mebel',
            name='description',
            field=models.TextField(verbose_name='Описание c Куфара'),
        ),
        migrations.AlterField(
            model_name='mebel',
            name='parse_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода к нам'),
        ),
    ]
